In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({'a':[1,2,3,4,5],'b':[6,7,8,9,0]},index=['i-1','i-2','i-3','i-4','i-5'])
df

     a  b
i-1  1  6
i-2  2  7
i-3  3  8
i-4  4  9
i-5  5  0

In [5]:
df.to_csv('test_export.csv')

In [8]:
df = pd.read_csv('test_import.csv',index_col=0)
df

     param1  param2  param3
i_0      11      12      13
i_1      21      22      23
i_3      31      21      33
i_4      41      42      43
i_5      51      52      53

# .read_csv
    .read_csv
    (
    filepath_or_buffer, 
    sep=',', 
    delimiter=None, 
    header=’infer’, 
    names=None, 
    index_col=None, 
    usecols=None, 
    squeeze=False, 
    prefix=None, 
    mangle_dupe_cols=True, 
    dtype=None, 
    engine=None, 
    converters=None, 
    true_values=None, 
    false_values=None, 
    skipinitialspace=False, 
    skiprows=None, 
    nrows=None, 
    na_values=None, 
    keep_default_na=True, 
    na_filter=True, 
    verbose=False, 
    skip_blank_lines=True, 
    parse_dates=False, 
    infer_datetime_format=False, 
    keep_date_col=False, 
    date_parser=None, 
    dayfirst=False, 
    iterator=False, 
    chunksize=None, 
    compression=’infer’, 
    thousands=None, 
    decimal=b’.’, 
    lineterminator=None, 
    quotechar=’”’, 
    quoting=0, 
    escapechar=None, 
    comment=None, 
    encoding=None, 
    dialect=None, 
    tupleize_cols=None, 
    error_bad_lines=True, 
    warn_bad_lines=True, 
    skipfooter=0, 
    skip_footer=0, 
    doublequote=True, 
    delim_whitespace=False, 
    as_recarray=None, 
    compact_ints=None, 
    use_unsigned=None, 
    low_memory=True, 
    buffer_lines=None, 
    memory_map=False, 
    float_precision=None
    ) 

``` filepath_or_buffer : 路径 URL 可以是http, ftp, s3, 和 file.

    sep: 指定分割符，默认是’,’C引擎不能自动检测分隔符，但Python解析引擎可以

    delimiter: 同sep

    delimiter_whitespace: True or False 默认False, 用空格作为分隔符等价于spe=’\s+’如果该参数被调用，则delimite不会起作用

    header: 指定第几行作为列名(忽略注解行)，如果没有指定列名，默认header=0; 如果指定了列名header=None

    names 指定列名，如果文件中不包含header的行，应该显性表示header=None

    index_col: 默认为None 用列名作为DataFrame的行标签，如果给出序列，则使用MultiIndex。如果读取某文件,该文件每行末尾都有带分隔符，考虑使用index_col=False使panadas不用第一列作为行的名称。```

    ```
    usecols： 默认None 可以使用列序列也可以使用列名，如 [0, 1, 2] or [‘foo’, ‘bar’, ‘baz’]

    as_recarray：默认False , 将读入的数据按照numpy array的方式存储，0.19.0版本后使用
    pd.read_csv(…).to_records()。 注意，这种方式读入的na数据不是显示na,而是给以个莫名奇妙的值

    squeeze: 默认为False, True的情况下返回的类型为Series

    prefix:默认为none, 当header =None 或者没有header的时候有效，例如’x’ 列名效果 X0, X1, …

    mangle_dupe_cols ：默认为True,重复的列将被指定为’X.0’…’X.N’，而不是’X’…’X’。如果传入False，当列中存在重复名称，则会导致数据被覆盖。

    dtype: E.g. {‘a’: np.float64, ‘b’: np.int32} 指定数据类型

    engine: {‘c’, ‘python’}, optional 选择读取的引擎目前来说C更快，但是Python的引擎有更多选择的操作

    skipinitialspace: 忽略分隔符后的空格,默认false,

    skiprows: list-like or integer or callable, default None 忽略某几行或者从开始算起的几行

    skipfooter: 从底端算起的几行，不支持C引擎

    nrows： int 读取的行数

    na_values: 默认None NaN包含哪些情况，默认情况下, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’. 都表现为NAN

    keep_default_na: 如果na_values被定义,keep_default_na为False那么默认的NAN会被改写。 默认为True

    na_filter: 默认为True, 针对没有NA的文件，使用na_filter=false能够提高读取效率

    skip_blank_lines 默认为True,跳过blank lines 而且不是定义为NAN

    thousands 千分位符号，默认‘，’

    decimal 小数点符号，默认‘.’

    encoding: 编码方式

    memory_map如果为filepath_or_buffer提供了文件路径，则将文件对象直接映射到内存上，并直接从那里访问数据。使用此选项可以提高性能，因为不再有任何I / O开销。

    low_memory 默认为True 在块内部处理文件，导致分析时内存使用量降低，但可能数据类型混乱。要确保没有混合类型设置为False，或者使用dtype参数指定类型。请注意，不管怎样，整个文件都读入单个DataFrame中，请使用chunksize或iterator参数以块形式返回数据。```